import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{
          backgroundColor:"lightblue",
          color:"black",
          display:"flex",
          justifyContent:"center"
        }}>
          <h1>Headers</h1>
        </header>
        {children}
        <footer style={{
          backgroundColor:"teal",
          color:"white"
        }}>
          <h1>This is the footer</h1>

        </footer>
      </body>
    </html>
  );
}
